# Generated by Django 5.1.4 on 2025-09-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Бренд')),
                ('ext_id', models.CharField(blank=True, max_length=100, verbose_name='Внешний ID у конкурента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='stock.competitor', verbose_name='Конкурент')),
            ],
            options={
                'verbose_name': 'Бренд конкурента',
                'verbose_name_plural': 'Бренды конкурентов',
                'indexes': [models.Index(fields=['competitor', 'name'], name='stock_compe_competi_abfd91_idx')],
                'constraints': [models.UniqueConstraint(fields=('competitor', 'name'), name='uniq_competitor_brand')],
            },
        ),
    ]
