# Generated by Django 5.1.4 on 2025-09-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_competitorbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorproduct',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='competitorproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.competitorbrand', verbose_name='Бренд'),
        ),
    ]
