# Generated by Django 5.1.4 on 2025-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_competitorproduct_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorpricestocksnapshot',
            name='price_inc_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена с НДС'),
        ),
    ]
