# Generated by Django 5.1.4 on 2025-09-22 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_competitorpricestocksnapshot_price_inc_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ext_id', models.CharField(max_length=50, verbose_name='Внешний ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Уровень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stock.competitor', verbose_name='Конкурент')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stock.competitorcategory', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория конкурента',
                'verbose_name_plural': 'Категории конкурентов',
            },
        ),
        migrations.AddField(
            model_name='competitorproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.competitorcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='competitorcategory',
            index=models.Index(fields=['competitor', 'ext_id'], name='stock_compe_competi_5d1e67_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorcategory',
            index=models.Index(fields=['competitor', 'parent', 'title'], name='stock_compe_competi_bc7fb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitorcategory',
            constraint=models.UniqueConstraint(fields=('competitor', 'ext_id'), name='uniq_competitor_category_ext'),
        ),
    ]
