# Generated by Django 5.1.4 on 2025-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_competitorcategory_competitorproduct_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='b2b_site_url',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='competitorcategory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='competitor',
            name='data_source_type',
            field=models.CharField(blank=True, choices=[('ftp', 'FTP'), ('https', 'HTTPS')], help_text='Как получаем данные от конкурента', max_length=20, null=True, verbose_name='Тип источника данных'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='data_url',
            field=models.CharField(blank=True, help_text='Для FTP: хост (напр. ftp.example.com); для HTTPS: ссылка на файл', max_length=500, verbose_name='URL или хост'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Логин'),
        ),
    ]
