# Generated by Django 5.1.4 on 2025-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_competitor_b2b_site_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorproduct',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='part_number',
            field=models.CharField(help_text='Обозначение позиции у конкурента', max_length=512, verbose_name='Part number / SKU'),
        ),
    ]
