# Generated by Django 5.1.4 on 2025-10-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_fileblob_productfile'),
        ('stock', '0007_alter_competitorproduct_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competitorproduct',
            name='uniq_competitor_part',
        ),
        migrations.AddConstraint(
            model_name='competitorproduct',
            constraint=models.UniqueConstraint(fields=('competitor', 'ext_id'), name='uniq_competitor_part'),
        ),
    ]
