# Generated by Django 5.1.4 on 2025-10-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_fileblob_productfile'),
        ('stock', '0008_remove_competitorproduct_uniq_competitor_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('moment', models.DateTimeField(db_index=True, verbose_name='Момент изменения')),
                ('stock_qty', models.IntegerField(blank=True, null=True, verbose_name='Количество на складе')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='goods.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Снимок склада (наши)',
                'verbose_name_plural': 'Снимки складов (наши)',
                'ordering': ['-moment'],
                'indexes': [models.Index(fields=['product', 'moment'], name='stock_ourst_product_ec22da_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'moment'), name='uniq_our_stock_per_moment')],
            },
        ),
    ]
