# Generated by Django 5.1.4 on 2025-10-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_ourstocksnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourstocksnapshot',
            name='raw_payload',
        ),
    ]
