# Generated by Django 5.1.4 on 2025-10-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_ourstocksnapshot_raw_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstocksnapshot',
            name='cost_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Затраты'),
        ),
        migrations.AddField(
            model_name='ourstocksnapshot',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Наценка'),
        ),
    ]
