# Generated by Django 5.1.4 on 2025-10-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_ourstocksnapshot_cost_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstocksnapshot',
            name='cost_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Затраты'),
        ),
        migrations.AlterField(
            model_name='ourstocksnapshot',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Наценка'),
        ),
    ]
