# Generated by Django 5.1.4 on 2025-10-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_ourstocksnapshot_cost_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstocksnapshot',
            name='rmb_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Курс юаня'),
        ),
        migrations.AddField(
            model_name='ourstocksnapshot',
            name='usd_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Курс доллара'),
        ),
    ]
