# Generated by Django 5.1.4 on 2025-08-12 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_manager',
            field=models.ForeignKey(blank=True, help_text='Если не указан, используется менеджер бренда или подгруппы', limit_choices_to={'role': 'purchaser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
    ]
