# Generated by Django 5.1.4 on 2025-08-12 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_product_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='product_manager',
            field=models.ForeignKey(blank=True, help_text='Менеджер, отвечающий за данный бренд', limit_choices_to={'role': 'purchaser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер за бренд'),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='product_manager',
            field=models.ForeignKey(blank=True, help_text='Менеджер, отвечающий за данную подгруппу', limit_choices_to={'role': 'purchaser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subgroups', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
    ]
