# Generated by Django 5.1.4 on 2025-08-22 15:56

import django.db.models.deletion
import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_brand_product_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(help_text='Уникальный хэш содержимого', max_length=64, unique=True, verbose_name='SHA-256')),
                ('file', models.FileField(upload_to=goods.models.file_blob_upload_path, verbose_name='Файл')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер, байт')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бинарный файл',
                'verbose_name_plural': 'Бинарные файлы',
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('datasheet', 'Даташит'), ('drawing', 'Чертеж'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип файла')),
                ('source_url', models.URLField(blank=True, help_text='URL, откуда файл был скачан', max_length=500, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_files', to='goods.fileblob', verbose_name='Файл')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='goods.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Файл товара',
                'verbose_name_plural': 'Файлы товара',
                'indexes': [models.Index(fields=['product', 'file_type'], name='goods_produ_product_ca4b2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'file_type'), name='uniq_product_type')],
            },
        ),
    ]
