# Generated by Django 5.1.4 on 2025-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_db_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='old db name'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchaser', 'Purchaser'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=255, verbose_name='role'),
        ),
    ]
