# Generated by Django 5.1.4 on 2025-08-25 20:44

import rfqs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='ext_id',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='ext_id',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='ext_id',
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='rfqitemfile',
            name='file',
            field=models.FileField(upload_to=rfqs.models.rfq_file_upload_path, validators=[rfqs.models.validate_rfq_item_file_size], verbose_name='Файл'),
        ),
    ]
