# Generated by Django 5.1.4 on 2025-08-25 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0002_remove_quotation_ext_id_remove_rfq_ext_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='ext_id',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='title',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
