# Generated by Django 5.1.4 on 2025-08-26 18:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0003_remove_quotationitem_ext_id_remove_rfq_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='cost_expense_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Процент затрат, включаемых в стоимость (например, логистика, НДС, издержки)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент затрат'),
        ),
    ]
