# Generated by Django 5.1.4 on 2025-09-15 20:27

import django.db.models.deletion
import rfqs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0004_quotationitem_cost_expense_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=rfqs.models.quotation_item_file_upload_path, validators=[rfqs.models.validate_quotation_item_file_size], verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('photo', 'Фотография'), ('datasheet', 'Даташит'), ('specification', 'Спецификация'), ('drawing', 'Чертеж'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип файла')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='rfqs.quotationitem', verbose_name='Строка предложения')),
            ],
            options={
                'verbose_name': 'Файл строки предложения',
                'verbose_name_plural': 'Файлы строк предложения',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
